name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run: cargo clean
    - name: Build cli
      run: cargo build --feature cli --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build wasm
      run: cargo build --feature wasm --verbose
    - name: Run tests wasm
      run: cargo test --verbose
